name: fal
description: First Auto Link.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.19.1
  cupertino_icons: ^1.0.0
  shared_preferences: ^2.0.3
  bottom_sheet_bar: ^2.0.0
  image_picker: ^0.7.2+1
  eva_icons_flutter: ^2.0.1
  flare_flutter: ^2.0.6
  gradient_widgets: ^0.5.2
  liquid_swipe: ^1.5.0
  url_launcher: ^5.5.0
  fl_chart: ^0.9.4
  multi_image_picker: ^4.8.0
  intl: ^0.17.0
  badges: ^1.2.0
  geolocator: ^6.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:

  uses-material-design: true
  
  assets:
    - assets/images/

  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Light.ttf
          weight: 100
        - asset: assets/fonts/Oxygen-Bold.ttf
          weight: 500  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700